### ISSUE TITLE
GoogleTest (and hence ROOT with testing on) fails to build on GCC 4.8.5

### ISSUE THREAD

**Issue by egpbos** [root-project/root#9370]
- [x] Checked for duplicates

### Describe the bug
When compiling with GCC c++ 4.8.5, GoogleTest fails to build. A sample of messages:

```
In file included from /user/pbos/project_atlas/root-20211202/cmake-build-release/googletest-prefix/src/googletest/googletest/include/gtest/internal/gtest-death-test-internal.h:39:0,
                 from /user/pbos/project_atlas/root-20211202/cmake-build-release/googletest-prefix/src/googletest/googletest/include/gtest/gtest-death-test.h:41,
                 from /user/pbos/project_atlas/root-20211202/cmake-build-release/googletest-prefix/src/googletest/googletest/include/gtest/gtest.h:64,
                 from /user/pbos/project_atlas/root-20211202/cmake-build-release/googletest-prefix/src/googletest/googletest/src/gtest-all.cc:38:
/user/pbos/project_atlas/root-20211202/cmake-build-release/googletest-prefix/src/googletest/googletest/include/gtest/gtest-matchers.h: In static member function ‘static constexpr bool testing::internal::MatcherBase<T>::IsInlined()’:
/user/pbos/project_atlas/root-20211202/cmake-build-release/googletest-prefix/src/googletest/googletest/include/gtest/gtest-matchers.h:414:12: error: ‘is_trivially_copy_constructible’ is not a member of ‘std’
            std::is_trivially_copy_constructible<M>::value &&
            ^
/user/pbos/project_atlas/root-20211202/cmake-build-release/googletest-prefix/src/googletest/googletest/include/gtest/gtest-matchers.h:414:50: error: expected primary-expression before ‘>’ token
            std::is_trivially_copy_constructible<M>::value &&
                                                  ^
/user/pbos/project_atlas/root-20211202/cmake-build-release/googletest-prefix/src/googletest/googletest/include/gtest/gtest-matchers.h:414:51: error: ‘::value’ has not been declared
            std::is_trivially_copy_constructible<M>::value &&
                                                   ^
```
There is more, but I think this already indicates that one of the issues is the GCC version, since `is_trivially_copy_constructible` is available from GCC 5.

### Expected behavior
CMake should not configure successfully on GCC versions below 5 when configuring with `-Dtesting=ON`.

### To Reproduce

A system with GCC 4.8.5 is necessary, but probably the issue will also be triggered with other 4.8.x versions. Then, configure from the build dir with `cmake .. -Dtesting=ON` (actually, I was configuring with `cmake .. -Droofit_multiprocess=ON -Dminuit2=ON -Dtesting=ON`, but probably the first two options are not necessary). Build with `make` and it should crash, with the logs showing the above quoted messages.

### Setup
1. ROOT version: master
2. Operating system: CentOS 7
3. How you obtained ROOT, such as `dnf install` / binary download / you built it yourself: source build from GitHub.

### Additional context
None.

**Comment by vgvassilev** [comment]
@Axel-Naumann, do we still support that compiler version?

**Comment by Axel-Naumann** [comment]
We don't (as we require C++14 these days). And thus @egpbos is correct when stating:

> CMake should not configure successfully on GCC versions below 5 when configuring with -Dtesting=ON.

**Comment by egpbos** [comment]
4.8 is still mentioned in the dependencies here: https://root.cern/install/dependencies/

**Comment by guitargeek** [comment]
We have successfully waited out the issue! ROOT 6.28 already doesn't support 4.8 anymore:
https://root.cern/install/dependencies/
