### ISSUE TITLE
Cling not recognizing __sincospif on MacOS (from math.h)

### ISSUE THREAD

**Issue by pcanal** [root-project/root#14442]
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

`Cling` is not seeing of the content of `math.h` on MacOS.

### Reproducer

With the file header.h
```
#include <math.h>

void func()
{
   float a = 0, b = 0, c = 0;
   __sincospif(a, &b, &c);
}
```
the file compiles:
```
clang++ -c header.h 
clang: warning: treating 'c-header' input as 'c++-header' when in C++ mode, this behavior is deprecated [-Wdeprecated]
```
but fails to be parsed by `Cling` (well `rootcling`)
```
rootcling -f dict.cxx header.h
In file included from input_line_8:3:
header.h:6:4: error: use of undeclared identifier '__sincospif'
   __sincospif(a, &b, &c);
   ^
Error: rootcling: compilation failure (dict51adc8b8cb_dictUmbrella.h)
```

### ROOT version

Tested on master likely also on older releases.

### Installation method

manual build and/or spack

### Operating system

MacOS

**Comment by dpiparo** [comment]
adding @devajithvs , maybe he has ideas.

**Comment by dpiparo** [comment]
It works on master and 6.34 on macOS 15. It's likely that the evolution of the interpreter fixed it - at this point, once a test is added, the issue can be closed.

**Comment by Aditya-138-12** [comment]
Hi @dpiparo @devajithvs @pcanal @vgvassilev 
I was thinking on this, if we will add a test for this, the CI would run it on all the operating systems, so would it not fail for all of them and just pass on Mac OS?
Would love to know more about this!!

**Comment by Aditya-138-12** [comment]
I also tried compiling this test on Ubuntu 24.04.2 LTS, and got this error

![Image](https://github.com/user-attachments/assets/1e589353-bfbd-43cc-9c96-ed9e43acde57)

**Comment by dpiparo** [comment]
This is now fixed, for master as well as for 6.36.
