### PR TITLE
[cling] interpreter/CMakeLists.txt: correct CLANG_INCLUDE_DIRS

### PR DESCRIPTION
**Pull request by veprbl**
This looks like a regression from https://github.com/root-project/root/commit/7a1cc8ffe576490b2f977ba2c262e10ec53a797a#diff-93558e500b17901f800fbb40a2c2fdfd6ee229077db63413bd4a91ee7ec66ea7. It seems like interpreter/llvm-project/llvm/tools/clang would not be a thing, while a following compilation error is observed with builtin_llvm=OFF:

    In file included from interpreter/cling/lib/Utils/AST.cpp:12:
    In file included from interpreter/llvm-project/clang/include/clang/AST/ASTContext.h:18:
    interpreter/llvm-project/clang/include/clang/AST/ASTFwd.h:21:10: fatal error: 'clang/AST/DeclNodes.inc' file not found
    #include "clang/AST/DeclNodes.inc"
             ^~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

# This Pull request:

## Checklist:

- [x] tested changes locally
- [ ] updated the docs (if necessary)

This PR fixes #

### CODE REVIEW

File: interpreter/CMakeLists.txt [hunk 1]
```diff
@@ -459,7 +459,7 @@ if (builtin_clang)
   endif()
   set(CLANG_INCLUDE_DIRS
     ${CMAKE_SOURCE_DIR}/interpreter/llvm-project/clang/include
-    ${CMAKE_BINARY_DIR}/interpreter/llvm-project/llvm/tools/clang/include
+    ${CMAKE_BINARY_DIR}/interpreter/llvm-project/clang/include
```
Comment (hahnjo) [inline interpreter/CMakeLists.txt:462]: Unfortunately, this breaks the configuration with `builtin_llvm=ON`. Looking a bit around, I think what we want is
```suggestion
    ${Clang_DIR}/include
```
This works on my system for both settings of `builtin_llvm`. Can you maybe check on your end?

**Review by hahnjo — CHANGES_REQUESTED** [review]
Just to be sure we are on one page here: The errors happen when you configure with `builtin_llvm=OFF` but `builtin_clang=ON` (which is the default)? If yes, I can reproduce the problem, sorry for breaking this. Please see my comment / suggestion inline.

File: interpreter/CMakeLists.txt (hunk 1 above)
Comment (veprbl) [reply interpreter/CMakeLists.txt]: That works too

**Comment by hahnjo** [comment]
@phsft-bot build

**Review by hahnjo — APPROVED** [review]
Thanks! This seems to work.

**Comment by guitargeek** [comment]
@veprbl @hahnjo, should be backport it to 6.30?

**Comment by hahnjo** [comment]
> @veprbl @hahnjo, should be backport it to 6.30?

Yes, will do today :+1: (I only didn't merge on Saturday because I was lacking time to watch that everything works fine on `master` after it's in)
