### ISSUE TITLE
ROOT and Python 3.15

### ISSUE THREAD

**Issue by ellert** [root-project/root#21787]
### Check duplicate issues.

- [x] Checked for duplicates

### Description

Forwarded from downstream Fedora bugzilla ticket:
https://bugzilla.redhat.com/show_bug.cgi?id=2454247

root fails to build with Python 3.15.0a7.

Many many tests fail with the same traceback:
```
Traceback (most recent call last):
  File "/builddir/build/BUILD/root-6.38.04-build/root-6.38.04/tutorials/machine_learning/TMVA_RNN_Classification.py", line 21, in <module>
    import ROOT
  File "/builddir/build/BUILD/root-6.38.04-build/root-6.38.04/redhat-linux-build/lib/ROOT/__init__.py", line 99, in <module>
    _root_facade = ROOTFacade(sys.modules[__name__], _is_ipython)
  File "/builddir/build/BUILD/root-6.38.04-build/root-6.38.04/redhat-linux-build/lib/ROOT/_facade.py", line 65, in __init__
    self.__cached__ = module.__cached__
                      ^^^^^^^^^^^^^^^^^
AttributeError: partially initialized module 'ROOT' from '/builddir/build/BUILD/root-6.38.04-build/root-6.38.04/redhat-linux-build/lib/ROOT/__init__.py' has no attribute '__cached__' (most likely due to a circular import)
```

### Reproducer

Run tests with root build with Python 3.15.

### ROOT version

6.38.04

### Installation method

Built from source for RPM package build.

### Operating system

Fedora rawhide with Python 3.15 (special test repo preparing for Python update)

### Additional context

Python 3.15 is planned to be included in Fedora 45.

Logs from the test builds:
https://copr.fedorainfracloud.org/coprs/g/python/python3.15/package/root/

**Comment by dpiparo** [comment]
Thanks for this report: we'll address the problem.
We have in place a rawhide build to try to address this kind of issues early, however we still see Python 3.14 and not 15 there: I was naively expecting that rawhide could be seen as "the future fedora distro", but I was wrong.
Would you have some advice on how to try and prevent this kind of situations in the future?

**Comment by guitargeek** [comment]
It the original issue post:

> Fedora rawhide with Python 3.15 (special test repo preparing for Python update)


So it seems Fedora rawhide is planning the Python 3.15 upgrade, but one blocker is this problem with ROOT. So the snake is eating it's tail here 🙂 

Python 3.15 is still half a year from being released, so I think this situation where packagers report to use early what goes wrong is good. A ROOT CI workflow that tests the upcoming Python version even before even the beta is released is a bit too much in my opinion. But by the time of the Python release candidate we should have something, and by then Rawhide will have done the upgrade.

**Comment by guitargeek** [comment]
@ellert, thanks for reporting this by the way! I'm looking into it, with the Python 3.15 package on nix. This issue makes me a bit nervous because it's not the usual C Python API change-related problem that we see when upgrading Python, but something related to the ROOT module facade, which is a bit hacky and is would not be surprising if Python goes after these by requiring more correct module initialization.
