### PR TITLE
[TPython] Switch to Python limited API and delegate more to CPyCppyy

### PR DESCRIPTION
**Pull request by guitargeek**
Refactor TPython and related bindings to use the Python limited API (`Py_LIMITED_API`) where possible, removing direct dependencies on the full CPython interpreter embedding interface.

This decouples **TPython** from a specific Python version by avoiding the full CPython API, enabling future use of a pip-installable CPyCppyy CPython extension loaded at runtime.

### CODE REVIEW

File: bindings/pyroot/cppyy/CPyCppyy/src/API.cxx [hunk 1]
```diff
@@ -355,117 +355,58 @@ void CPyCppyy::ExecScript(const std::string& name, const std::vector<std::string
...
-   argv2.reserve(argc);
-   argv2.emplace_back(name.c_str(), &name[name.size()]);
-
-   for (int i = 1; i < argc; ++i) {
-      auto iarg = args[i - 1].c_str();
-      argv2.emplace_back(iarg, &iarg[strlen(iarg)]);
-   }
+// build new argv
+    const int argc = (int)args.size() + 1;
+    std::vector<wchar_t*> wargv(argc);
```
Comment (vepadulano) [inline bindings/pyroot/cppyy/CPyCppyy/src/API.cxx:368]: nitpick: if any exception is thrown during this function the memory allocated by the calls to `Py_DecodeLocale` won't be freed. Maybe consider using some RAII-like struct.

File: bindings/tpython/src/TPython.cxx [hunk 2]
```diff
@@ -134,43 +136,8 @@ Bool_t TPython::Initialize()
...
-         // give up ...
-         std::cerr << "Error: python has not been intialized; returning." << std::endl;
-         return false;
-      }
-
-#if PY_VERSION_HEX < 0x030b0000
-      PySys_SetArgv(argc, argv);
-#endif
+      // Trigger the Python initialization indirectly via CPyCppyy
+      CPyCppyy::Scope_Check(nullptr);
```
Comment (vepadulano) [inline bindings/tpython/src/TPython.cxx:140]: Question: is this underlining a need for a Python initialization API exposed by CPyCppyy?

Comment (guitargeek) [reply bindings/tpython/src/TPython.cxx:140]: I'm not sure, I think the TPython-like usecase of initializing the Python interpreter from a library is rather niche. And I would also not encourage people to do this more by having a public `Initialize()` API (at least for now).

File: bindings/pyroot/cppyy/CPyCppyy/src/API.cxx (hunk 1 above)
Comment (guitargeek) [reply bindings/pyroot/cppyy/CPyCppyy/src/API.cxx:368]: Good thinking, but I don't think CPython actually throws exceptions. Either the PyError is set and we have to handle it with early returns (doesn't happen here), or there will just be a plain crash, in which case we don't care if the memory was freed or not.

**Comment by smuzaffar** [comment]
@guitargeek , looks like this breaks root build with Python 3.9 in CMSSW . See full build log at https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-eae897/52329/externals/root/6.39.1-d644f2fca26df960fa8a6e4a26d960ff/log
```
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc13/lcg/root/6.39.1-d644f2fca26df960fa8a6e4a26d960ff/root-6.39.1/bindings/tpython/src/TPyClassGenerator.cxx: In member function 'virtual TClass* TPyClassGenerator::GetClass(const char*, Bool_t, Bool_t)':
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc13/lcg/root/6.39.1-d644f2fca26df960fa8a6e4a26d960ff/root-6.39.1/bindings/tpython/src/TPyClassGenerator.cxx:127:37: error: 'PyUnicode_AsUTF8AndSize' was not declared in this scope; did you mean 'PyUnicode_AsUTF8String'?
  127 |             const char *func_name = PyUnicode_AsUTF8AndSize(key, nullptr);
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~
      |                                     PyUnicode_AsUTF8String
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/BUILD/el8_amd64_gcc13/lcg/root/6.39.1-d644f2fca26df960fa8a6e4a26d960ff/root-6.39.1/bindings/tpython/src/TPyClassGenerator.cxx:235:35: error: 'PyUnicode_AsUTF8AndSize' was not declared in this scope; did you mean 'PyUnicode_AsUTF8String'?
  235 |          const char *mtNameCStr = PyUnicode_AsUTF8AndSize(label, nullptr);
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~
      |                                   PyUnicode_AsUTF8String

```

**Comment by guitargeek** [comment]
Thanks for the report! We are not actively supporting Python 3.9 anymore, because it is end-of-life. Do you really need it supported? Until when would you need it? We need to make concrete plans there, because we can't commit to support end-of-life Python versions indefinitely.

I can fix this concrete problem for your convenience if that would help you for the moment, but I would really appreciate some info on Python 3.9 usage in CMS so I can plan.

In particular, on `el8`, Python 3.9 is not even the default, so I'm a bit surprised you are using a non-default Python version that is at the same time EOL.

**Comment by smuzaffar** [comment]
We are planning to move to Python 3.12 for CMSSW_17_0_X (hopefully in 2nd of week of April). Also this failure is only for ROOT master based CMSSW builds, I guess we can already update CMSSW ROOT master to start using python 3.12
