### ISSUE TITLE
ROOT-master fails to compile with cuda (12.5) [tvma-gpu]

### ISSUE THREAD

**Issue by andresailer** [root-project/root#23485]
### Check duplicate issues.

- [x] Checked for duplicates

### Description

Since September 22 we see this

```
/build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-70994aa6/src/ROOT/70994aa6/tmva/tmva/inc/TMVA/DNN/Architectures/Cuda/CudaTensor.h:54:7: error: conflicting declaration 'using TMVA::DNN::MemoryLayout = enum class TMVA::Experimental::MemoryLayout'
   54 | using MemoryLayout = TMVA::Experimental::MemoryLayout;
      |       ^~~~~~~~~~~~
In file included from /build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-70994aa6/src/ROOT/70994aa6/tmva/tmva/inc/TMVA/DNN/Architectures/Cpu.h:32,
                 from /build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-70994aa6/src/ROOT/70994aa6/tmva/tmva/inc/TMVA/MethodDL.h:47,
                 from /build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-70994aa6/src/ROOT/70994aa6/tmva/tmva/src/MethodDL.cxx:37:
/build/jenkins/workspace/lcg_nightly_pipeline/build/projects/ROOT-70994aa6/src/ROOT/70994aa6/tmva/tmva/inc/TMVA/DNN/Architectures/Cpu/CpuTensor.h:37:12: note: previous declaration as 'enum class TMVA::DNN::MemoryLayout'
   37 | enum class MemoryLayout : uint8_t {
```

I think it comes from #23430

see 
* https://cdash.cern.ch/builds/39329/files/3672
* https://cdash.cern.ch/builds/40136/files/3706

### Reproducer

```
source /cvmfs/sft.cern.ch/lcg/nightlies/dev3cuda/Thu/Python/3.13.11/x86_64-el9-gcc13-opt/Python-env.sh
source /cvmfs/sft.cern.ch/lcg/nightlies/dev3cuda/Thu/jsonmcpp/3.12.0/x86_64-el9-gcc13-opt/jsonmcpp-env.sh
source /cvmfs/sft.cern.ch/lcg/nightlies/dev3cuda/Thu/tiff/4.7.1/x86_64-el9-gcc13-opt/tiff-env.sh
source /cvmfs/sft.cern.ch/lcg/nightlies/dev3cuda/Thu/GSL/2.8/x86_64-el9-gcc13-opt/GSL-env.sh
source /cvmfs/sft.cern.ch/lcg/nightlies/dev3cuda/Thu/gl2ps/1.4.2/x86_64-el9-gcc13-opt/gl2ps-env.sh
source /cvmfs/sft.cern.ch/lcg/nightlies/dev3cuda/Thu/fftw3/3.3.10/x86_64-el9-gcc13-opt/fftw-env.sh
source /cvmfs/sft.cern.ch/lcg/nightlies/dev3cuda/Thu/cfitsio/4.6.3/x86_64-el9-gcc13-opt/cfitsio-env.sh
source /cvmfs/sft.cern.ch/lcg/nightlies/dev3cuda/Thu/xrootd/6.1.1/x86_64-el9-gcc13-opt/xrootd-env.sh
source /cvmfs/sft.cern.ch/lcg/nightlies/dev3cuda/Thu/Davix/0.8.10/x86_64-el9-gcc13-opt/Davix-env.sh
source /cvmfs/sft.cern.ch/lcg/nightlies/dev3cuda/Thu/tbb/2023.1.0/x86_64-el9-gcc13-opt/tbb-env.sh
source /cvmfs/sft.cern.ch/lcg/nightlies/dev3cuda/Thu/vdt/0.4.4/x86_64-el9-gcc13-opt/vdt-env.sh
source /cvmfs/sft.cern.ch/lcg/nightlies/dev3cuda/Thu/Vc/1.4.5/x86_64-el9-gcc13-opt/Vc-env.sh
source /cvmfs/sft.cern.ch/lcg/nightlies/dev3cuda/Thu/protobuf/7.34.1/x86_64-el9-gcc13-opt/protobuf-env.sh
source /cvmfs/sft.cern.ch/lcg/nightlies/dev3cuda/Thu/ninja/1.13.2/x86_64-el9-gcc13-opt/ninja-env.sh
source /cvmfs/sft.cern.ch/lcg/nightlies/dev3cuda/Thu/cuda/12.5/x86_64-el9-gcc13-opt/cuda-env.sh
source /cvmfs/sft.cern.ch/lcg/nightlies/dev3cuda/Thu/civetweb/1.16p1/x86_64-el9-gcc13-opt/civetweb-env.sh
source /cvmfs/sft.cern.ch/lcg/nightlies/dev3cuda/Thu/cudnn/9.26.0.51/x86_64-el9-gcc13-opt/cudnn-env.sh

mkdir -p buildWithCuda
cd buildWithCuda
cmake \
   -DCMAKE_BUILD_TYPE=Release \
   -DCMAKE_INSTALL_PREFIX=${PWD}/../install \
   -DCMAKE_CXX_STANDARD=20 \
   -Dcheck_connection=OFF \
   -DCINTLONGLINE=4096 \
   -DCINTMAXSTRUCT=36000 \
   -DCINTMAXTYPEDEF=36000 \
   -DPYTHON_EXECUTABLE=`which python` \
   -Dbuiltin_civetweb=OFF \
   -Dbuiltin_ftgl=ON \
   -Dbuiltin_glew=ON \
   -Dbuiltin_lz4=ON \
   -Dbuiltin_pcre=ON \
   -Dbuiltin_unuran=ON \
   -Dbuiltin_xxhash=ON \
   -Dbuiltin_zstd=ON \
   -Dcintex=ON \
   -Dexplicitlink=ON \
   -Dfail-on-missing=ON \
   -Dfftw3=ON \
   -Dfitsio=ON \
   -Dfortran=ON \
   -Dgdml=ON \
   -Dgenvector=ON \
   -Dhttp=ON \
   -Dmathmore=ON \
   -Dopengl=ON \
   -Dpyroot=ON \
   -Dpythia8=OFF \
   -Dr=OFF \
   -Dreflex=ON \
   -Droofit=ON \
   -Droot7=ON \
   -Dssl=ON \
   -Dtesting=OFF \
   -Dunfold=ON \
   -Dunuran=ON \
   -Dxft=ON \
   -Dxml=ON \
   -Dxrootd=ON \
   -Dzlib=ON \
   -Dtmva-sofie=ON \
   -Ddavix=ON \
   -Dbuiltin_gif=ON \
   -Dbuiltin_jpeg=OFF \
   -Dbuiltin_png=OFF \
   -Droottest=OFF \
   -Dbuiltin_nlohmannjson=OFF \
   -Dtmva-gpu=ON \
   -DCMAKE_CUDA_ARCHITECTURES=all \
   -DCMAKE_CUDA_STANDARD=20 \
   -G Ninja ../
ninja
```

### ROOT version

master

### Installation method

from source

### Operating system

alma linux9

**Comment by guitargeek** [comment]
Thanks for the report! I'm on it.
