### PR TITLE
[cmake] Don't use ZMQ C++ headers from the system if ZMQ is too old

### LINKED ISSUE #10107: v6-26-00-patches branch fails to build on ubuntu 18.04
As reported [on the Forum](https://root-forum.cern.ch/t/build-error-in-the-v6-26-00-patches-branch-fails-to-build-on-ubuntu-18-04/49149):
This is Ubuntu 18.04 LTS / x86_64 / gcc, g++, gfortran 7.5.0 / cmake 3.20.3 here. The building of the current “v6-26-00-patches” branch (as of 2022.03.12) generates an error (“--std=c++14”):
```
(...)
In file included from /tmp/ROOT/v6-26-00-patches/roofit/roofitZMQ/src/ZeroMQSvc.cpp:14:0:
/tmp/ROOT/v6-26-00-patches/roofit/roofitZMQ/res/RooFit_ZMQ/ZeroMQSvc.h: In member function ‘void ZmqLingeringSocketPtrDeleter<PERIOD>::operator()(zmq::socket_t*)’:
/tmp/ROOT/v6-26-00-patches/roofit/roofitZMQ/res/RooFit_ZMQ/ZeroMQSvc.h:60:24: error: ‘class zmq::socket_t’ has no member named ‘set’; did you mean ‘send’?
                socket->set(zmq::sockopt::linger, PERIOD);
                        ^~~
                        send
/tmp/ROOT/v6-26-00-patches/roofit/roofitZMQ/res/RooFit_ZMQ/ZeroMQSvc.h:60:33: error: ‘zmq::sockopt’ has not been declared
                socket->set(zmq::sockopt::linger, PERIOD);
                                 ^~~~~~~
/tmp/ROOT/v6-26-00-patches/roofit/roofitZMQ/res/RooFit_ZMQ/ZeroMQSvc.h: At global scope:
/tmp/ROOT/v6-26-00-patches/roofit/roofitZMQ/res/RooFit_ZMQ/ZeroMQSvc.h:79:36: error: ‘unique_ptr’ in namespace ‘std’ does not name a template type
 using ZmqLingeringSocketPtr = std::unique_ptr<zmq::socket_t, ZmqLingeringSocketPtrDeleter<PERIOD>>;
                                    ^~~~~~~~~~
(...)
/tmp/ROOT/v6-26-00-patches/roofit/roofitZMQ/res/RooFit_ZMQ/ZeroMQSvc.h:103:6: error: no matching function for call to ‘zmq::socket_t::recv(std::reference_wrapper<zmq::message_t>&, int&)’
In file included from /tmp/ROOT/v6-26-00-patches/roofit/roofitZMQ/res/RooFit_ZMQ/ZeroMQSvc.h:17:0,
                 from /tmp/ROOT/v6-26-00-patches/roofit/roofitZMQ/res/RooFit_ZMQ/ZeroMQPoller.h:17,
                 from /tmp/ROOT/v6-26-00-patches/roofit/roofitZMQ/src/ZeroMQPoller.cpp:14:
/usr/include/zmq.hpp:625:23: note: candidate: size_t zmq::socket_t::recv(void*, size_t, int)
         inline size_t recv (void *buf_, size_t len_, int flags_ = 0)
                       ^~~~
/usr/include/zmq.hpp:625:23: note:   no known conversion for argument 1 from ‘std::reference_wrapper<zmq::message_t>’ to ‘void*’
/usr/include/zmq.hpp:635:21: note: candidate: bool zmq::socket_t::recv(zmq::message_t*, int)
         inline bool recv (message_t *msg_, int flags_ = 0)
                     ^~~~
/usr/include/zmq.hpp:635:21: note:   no known conversion for argument 1 from ‘std::reference_wrapper<zmq::message_t>’ to ‘zmq::message_t*’
In file included from /tmp/ROOT/v6-26-00-patches/roofit/roofitZMQ/res/RooFit_ZMQ/ZeroMQPoller.h:17:0,
                 from /tmp/ROOT/v6-26-00-patches/roofit/roofitZMQ/src/ZeroMQPoller.cpp:14:
(...)
/tmp/ROOT/v6-26-00-patches/roofit/roofitZMQ/src/ZeroMQPoller.cpp:231:14: error: ‘m_fds’ was not declared in this scope
    auto it = m_fds.find(fd);
              ^~~~~
/tmp/ROOT/v6-26-00-patches/roofit/roofitZMQ/src/ZeroMQPoller.cpp:231:14: note: suggested alternative: ‘m_free’
    auto it = m_fds.find(fd);
              ^~~~~
              m_free
Consolidate compiler generated dependencies of target obj.clingInterpreter
[ 73%] Built target obj.clingInterpreter
[ 73%] Built target clingInterpreter
[ 73%] Built target CLING
[ 73%] Built target clad
[ 73%] Built target LLVMRES
Consolidate compiler generated dependencies of target ClingUtils
roofit/roofitZMQ/CMakeFiles/RooFitZMQ.dir/build.make:89: recipe for target 'roofit/roofitZMQ/CMakeFiles/RooFitZMQ.dir/src/ZeroMQPoller.cpp.o' failed
make[2]: *** [roofit/roofitZMQ/CMakeFiles/RooFitZMQ.dir/src/ZeroMQPoller.cpp.o] Error 1
make[2]: Target 'roofit/roofitZMQ/CMakeFiles/RooFitZMQ.dir/build' not remade because of errors.
CMakeFiles/Makefile2:35161: recipe for target 'roofit/roofitZMQ/CMakeFiles/RooFitZMQ.dir/all' failed
make[1]: *** [roofit/roofitZMQ/CMakeFiles/RooFitZMQ.dir/all] Error 2
(...)
```
It seems that the problem is related to the system provided "`libzmq`".
The configuration step says:
`-- ZeroMQ not found. Switching on builtin_zeromq option`
but it also finds:
`pkgcfg_lib_PC_LIBZMQ_zmq:FILEPATH=/usr/lib/x86_64-linux-gnu/libzmq.so`
and then it uses the system provided `/usr/include/zmq.hpp` (from the "`libzmq3-dev 4.2.5-1ubuntu0.2`" package).

### PR DESCRIPTION
**Pull request by guitargeek**
If the ZeroMQ system version is too old, we can't use the system C++
headers either (note that `find_package(ZeroMQ)` not only checks if the
library exists, but also if it's a recent version with zmq_ppoll).

Therefore, we should also enable `builtin_cppzmq` if no usable ZMQ
version is found, not only `builtin_zeromq`.

This closes #10107.

@egpbos, FYI

### CODE REVIEW

File: cmake/modules/SearchInstalledSoftware.cmake [hunk 1]
```diff
@@ -1894,6 +1894,10 @@ if (roofit_multiprocess)
       if(NOT ZeroMQ_FOUND)
         message(STATUS "ZeroMQ not found. Switching on builtin_zeromq option")
         set(builtin_zeromq ON CACHE BOOL "Enabled because ZeroMQ not found (${builtin_zeromq_description})" FORCE)
+        # If the ZeroMQ system version is too old, we can't use the system C++
+        # headers either (note that find_package(ZeroMQ) not only checks if the
+        # library exists, but also if it's a recent version with zmq_ppoll).
+        set(builtin_cppzmq ON CACHE BOOL "Enabled because ZeroMQ not found (${builtin_cppzmq_description})" FORCE)
```
[the remark this answers is not in the document]
Comment (guitargeek) [reply cmake/modules/SearchInstalledSoftware.cmake:1900]: It's not the same line, the previous line is for `builtin_zeromq` and this one is for `builtin_cppzmq`.

Yes, actually it would have also been possible to check the `cppzmq` version number, as `zmq.hpp` has some preprocessor macros to indicate the version. But I think it's not worth to do this check, because usually on the system the `cppzmq` bindings come synchronized with `zeromq` and for this we already check the version in `find_package`.

That's why I thought it's simpler to just take the result of `find_package(ZeroMQ)` and enable/disable both `builtin_zeromq` and `builtin_cppzmq` simultaneously according to that.

**Review by lmoneta — APPROVED** [review]
Thank you for this quick fix!
