### ISSUE TITLE
Backward incompatible changes to RooNLLVar constructors

### ISSUE THREAD

**Issue by tomlatham** [root-project/root#8976]
- [x] Checked for duplicates

### Describe the bug
The changes introduced in PR #7616 have the side effect of breaking existing use of the RooNLLVar constructor where it is specified that the PDF is extended but the defaults for all further arguments are accepted, e.g.
`nllVar_ = new RooNLLVar("nllVar", "", model_, *exptData_, extended_);`
where `model_` is a `RooAddPdf`, `exptData_` is a `RooDataSet*` and `extended_` is a `bool`.

This appears to be due to the reordering of the `extended` argument to the two constructors:
```
  RooNLLVar(const char *name, const char *title, RooAbsPdf& pdf, RooAbsData& data,
            RooAbsTestStatistic::Configuration const& cfg, bool extended);
  
  RooNLLVar(const char *name, const char *title, RooAbsPdf& pdf, RooAbsData& data,
            const RooArgSet& projDeps, RooAbsTestStatistic::Configuration const& cfg,
            bool extended = false) ;
```
where previously the `extended` argument followed `data` in the first case and `projDeps` in the second.
Is it possible to swap back the order of the `extended` and `cfg` arguments and provide a default for `cfg`?
I think this should restore backward compatibility in this scenario.

### To Reproduce

```
source /cvmfs/sft.cern.ch/lcg/views/setupViews.sh dev3/latest x86_64-centos7-gcc11-opt
git clone https://phab.hepforge.org/source/laura.git
mkdir build install
cmake -S $PWD/laura -B $PWD/build -DLAURA_BUILD_ROOFIT_TASK=ON -DCMAKE_INSTALL_PREFIX=$PWD/install
cd build
make
```
This will result in a compilation error when trying to compile `LauRooFitTask.cc`:
```
error: no matching function for call to ‘RooNLLVar::RooNLLVar(const char [7], const char [1], RooAbsPdf&, RooAbsData&, const Bool_t&)’
```
Attempting the same build with LCG_100 or even dev4/latest does not produce the same error.

**Comment by guitargeek** [comment]
You are right! I was not taking care about the new interface being backwards compatible, because these constructors are considered as RooFit internal. But of course it doesn't hurt to make them backwards compatible either :)

I opened a PR to do that: https://github.com/root-project/root/pull/8986

**Comment by tomlatham** [comment]
Many thanks!
