### ISSUE TITLE
Module merge problems with GCC 13, C++20, Pythia8

### ISSUE THREAD

**Issue by hahnjo** [root-project/root#14217]
### Description

A C++ build of ROOT with GCC 13 works fine and passes all tests, *unless* also enabling Pythia8. Then suddenly `roottest-root-meta-MakeProject-examples` starts failing, as demonstrated with https://github.com/root-project/root/pull/14216:
```
  In module 'std' imported from input_line_1:1:
  /usr/lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/stl_pair.h:305:7: error: 'std::pair<const int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > >::pair' from module 'std.bits_stl_iterator_h' is not present in definition of 'std::pair<const int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > >' in module 'std.bits_stl_iterator_h'
        pair(const _T1& __x, const _T2& __y)
        ^
  /usr/lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/stl_pair.h:197:17: note: declaration of 'pair' does not match
        constexpr pair(const pair&) = default;    ///< Copy constructor
                  ^
  /usr/lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/stl_pair.h:198:17: note: declaration of 'pair' does not match
        constexpr pair(pair&&) = default;         ///< Move constructor
                  ^
  /usr/lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/stl_pair.h:202:2: note: declaration of 'pair' does not match
          pair(piecewise_construct_t, tuple<_Args1...>, tuple<_Args2...>);
          ^
  /usr/lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/stl_pair.h:238:2: note: declaration of 'pair' does not match
          pair(tuple<_Args1...>&, tuple<_Args2...>&,
          ^
  /usr/lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/stl_pair.h:249:7: note: declaration of 'pair' does not match
        pair()
        ^
  /usr/lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/stl_pair.h:305:7: note: declaration of 'pair' does not match
        pair(const _T1& __x, const _T2& __y)
        ^
  /usr/lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/stl_pair.h:315:2: note: declaration of 'pair' does not match
          pair(_U1&& __x, _U2&& __y)
          ^
  /usr/lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/stl_pair.h:323:2: note: declaration of 'pair' does not match
          pair(_U1&&, _U2&&) = delete;
          ^
  /usr/lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/stl_pair.h:330:2: note: declaration of 'pair' does not match
          pair(const pair<_U1, _U2>& __p)
          ^
  /usr/lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/stl_pair.h:339:2: note: declaration of 'pair' does not match
          pair(const pair<_U1, _U2>&) = delete;
          ^
  /usr/lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/stl_pair.h:345:2: note: declaration of 'pair' does not match
          pair(pair<_U1, _U2>&& __p)
          ^
  /usr/lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/stl_pair.h:354:2: note: declaration of 'pair' does not match
          pair(pair<_U1, _U2>&&) = delete;
          ^
```

### Reproducer

Build with GCC 13, `CMAKE_CXX_STANDARD=20`, and Pythia8 8.310.

### ROOT version

`master`

### Installation method

from source

### Operating system

Linux

**Comment by hahnjo** [comment]
Still there, see latest rebase of https://github.com/root-project/root/pull/14216

**Comment by hahnjo** [comment]
This seems fixed with the upgrade to LLVM 18 :partying_face:
