### ISSUE TITLE
Compilation failure with g++ 12.2 and C++20

### ISSUE THREAD

**Issue by bernhardmgruber** [root-project/root#12037]
### Describe the bug
ROOT master (c8ad00846344c090c3a6f653e0decf38ad324d65) fails to build with g++ 12.2 with `cmake -DCMAKE_CXX_STANDARD=20`. The reported error is:
```
In file included from /home/bgruber/dev/root/interpreter/llvm/src/include/llvm/Support/BinaryStreamReader.h:16,
                 from /home/bgruber/dev/root/interpreter/llvm/src/lib/Support/BinaryStreamReader.cpp:9:
/home/bgruber/dev/root/interpreter/llvm/src/include/llvm/Support/BinaryStreamArray.h:331:31: error: expected unqualified-id before ‘const’
  331 |   FixedStreamArrayIterator<T>(const FixedStreamArrayIterator<T> &Other)
      |                               ^~~~~
/home/bgruber/dev/root/interpreter/llvm/src/include/llvm/Support/BinaryStreamArray.h:331:31: error: expected ‘)’ before ‘const’
  331 |   FixedStreamArrayIterator<T>(const FixedStreamArrayIterator<T> &Other)
      |                              ~^~~~~
      |                               )
```

Checking out the offending file:
```c++
template <typename T>
class FixedStreamArrayIterator
    : public iterator_facade_base<FixedStreamArrayIterator<T>,
                                  std::random_access_iterator_tag, const T> {

public:
  FixedStreamArrayIterator(const FixedStreamArray<T> &Array, uint32_t Index)
      : Array(Array), Index(Index) {}

  FixedStreamArrayIterator<T>(const FixedStreamArrayIterator<T> &Other) // ERROR HERE
      : Array(Other.Array), Index(Other.Index) {}
...
```
indeed looks like wrong C++ syntax (the constructor shall only be named via an id-expression referring to the injected class name, see [here](https://eel.is/c++draft/class.ctor#general-1)). The `<T>` should be removed. The issue was fixed in upstream LLVM with [this commit](https://github.com/llvm/llvm-project/commit/2ccf0b76bcaf0895e04f14e3ff53c59dd96f9f0f). Please consider cherry-picking this commit.

### To Reproduce
1. git clone ROOT master
2. `cmake -DCMAKE_CXX_STANDARD=20`
3. `make`

### Setup

* gcc 12.2
* Ubuntu 22.10

**Comment by jalopezg-git** [comment]
This will be fixed once https://github.com/root-project/root/pull/11874 is merged.  We have still something to fix there though.

**Comment by bernhardmgruber** [comment]
Just tried again with 2eefa59bf1c3b2288b623b89c8e072abec8a79b3 (clean rebuild):
```c++
While building module 'Core':
While building module 'std' imported from input_line_1:1:
In file included from <module-includes>:1:
In file included from /usr/include/c++/12/algorithm:60:
In file included from /usr/include/c++/12/bits/stl_algobase.h:67:
In file included from /usr/include/c++/12/bits/stl_iterator.h:85:
In file included from /usr/include/c++/12/bits/stl_construct.h:62:
/usr/include/c++/12/bits/stl_iterator_base_funcs.h:81:5: error: redefinition of '__distance'
    __distance(_InputIterator __first, _InputIterator __last,
    ^
/usr/include/c++/12/bits/stl_iterator_base_funcs.h:81:5: note: previous definition is here
    __distance(_InputIterator __first, _InputIterator __last,
    ^
```

I guess there is still more to fix :)

**Comment by Axel-Naumann** [comment]
@vgvassilev see ^ - looks like we need more improvements for the modulemap?

**Comment by vgvassilev** [comment]
I asked the same question here: https://github.com/root-project/root/pull/11874#issuecomment-1410949749

What machine I could use to reproduce it - the machine I used for the C++20 support did not reproduce the same problem.

**Comment by Axel-Naumann** [comment]
The new CI in https://github.com/root-project/root/pull/12295 should show this (I hope); this should also allow you to exercise the new CI docker thingy from the developer side.

**Comment by bernhardmgruber** [comment]
I just tried again today with `CXX=g++13 cmake -DCMAKE_CXX_STANDARD=20 && make` and ROOT compiled fine (apart a few warnings)! Congratulations! I did not retry with g++12, the issue is resolved on my side!

**Comment by vgvassilev** [comment]
Cool. Let's click on the close button.
