### ISSUE TITLE
Build failure in Ubuntu 22.04 due to OpenSSL 3.0

### ISSUE THREAD

**Issue by ezradlesser** [root-project/root#10518]
### Describe the bug
ROOT v6.24.06 is currently failing to build in Ubuntu 22.04. This appears to be due to an upgrade to [OpenSSL 3.0](https://www.openssl.org/blog/blog/2021/09/07/OpenSSL3.Final/) with this new LTS release; you can see for example a similar issue [here](https://github.com/chris2511/xca/issues/320). The specific build error happens while building XROOTD. (I apologize in advance if this is not the correct place to report the issue.)

### Expected behavior
ROOT builds without error using latest OpenSSL.

### To Reproduce
1) Clean install of Ubuntu 22.04
2) `sudo apt update`, followed by `sudo apt upgrade` and `sudo apt install` the required libraries for building ROOT
3) Download ROOT source code and unzip
4) Configure & build (using system Python 3.10)

### Setup
ROOT version: v6-24-06
Operating system: Ubuntu 22.04 LTS (on Windows Subsystem for Linux / WSL2)
How you obtained ROOT: building from source

### Additional context
`root-v6-24-06/src/ROOT-build/XROOTD-prefix/src/XROOTD-stamp/XROOTD-build-*.log` files are attached:
[XROOTD-build-out.log](https://github.com/root-project/root/files/8613858/XROOTD-build-out.log)
[XROOTD-build-err.log](https://github.com/root-project/root/files/8613857/XROOTD-build-err.log)

The specific error from `XROOTD-build-err.log`:
`root-v6-24-06/src/ROOT-build/XROOTD-prefix/src/XROOTD/src/XrdCrypto/XrdCryptosslgsiAux.cc:901:32: error: invalid conversion from ‘const rsa_st*’ to ‘RSA*’ {aka ‘rsa_st*’} [-fpermissive]`

Finally, if it is helpful, the build script being used is [here](https://github.com/ezradlesser/heppy/blob/master/external/root/build.sh), with the only modification to the script being the `root_version` variable: `root_version=6-24-06`

**Comment by ferdymercury** [comment]
Can you try with most recent master? See https://github.com/root-project/root/issues/10496
And also https://github.com/root-project/root/pull/10322

**Comment by ezradlesser** [comment]
Thank you, @ferdymercury -- somehow I missed those previous issues... sorry about that.

Just to share here, I also tried with v6-22-08 from source and received the same XROOTD build error (but fewer warnings):
[XROOTD-build-out.log](https://github.com/root-project/root/files/8621472/XROOTD-build-out.log)
[XROOTD-build-err.log](https://github.com/root-project/root/files/8621473/XROOTD-build-err.log)

I then tried
```
$ cd ~
$ git clone https://github.com/root-project/root.git
$ mkdir root_build
$ cd root_build
$ cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=$(which gcc) -DCMAKE_CXX_COMPILER=$(which g++) -DCMAKE_Fortran_COMPILER=$(which gfortran) -S ../root -B ./
$ cmake --build .
```
and XROOTD seems to have built successfully, but there seems to be some other errors. The configure step said that the ROOT version is 6-27-01.
[build_out.log](https://github.com/root-project/root/files/8626646/build.log)
[build_err.log](https://github.com/root-project/root/files/8626647/build_err.log)

**Comment by ferdymercury** [comment]
> Thank you, @ferdymercury -- somehow I missed those previous issues... sorry about that.
> 
> Just to share here, I also tried with v6-22-08 from source and received the same XROOTD build error (but fewer warnings): [XROOTD-build-out.log](https://github.com/root-project/root/files/8621472/XROOTD-build-out.log) [XROOTD-build-err.log](https://github.com/root-project/root/files/8621473/XROOTD-build-err.log)
> 
> I then tried
> 
> ```
> $ cd ~
> $ git clone https://github.com/root-project/root.git
> $ mkdir root_build
> $ cd root_build
> $ cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=$(which gcc) -DCMAKE_CXX_COMPILER=$(which g++) -DCMAKE_Fortran_COMPILER=$(which gfortran) -S ../root -B ./
> $ cmake --build .
> ```
> 
> and XROOTD seems to have built successfully, but there seems to be some other errors. The configure step said that the ROOT version is 6-27-01. [build_out.log](https://github.com/root-project/root/files/8626646/build.log) [build_err.log](https://github.com/root-project/root/files/8626647/build_err.log)

@eguiraud seems similar to https://root-forum.cern.ch/t/error-for-installing-root-source-in-ubuntu-22-04/49803/21?u=ferhue

**Comment by ferdymercury** [comment]
"bits" error also appears on https://lcgapp-services.cern.ch/root-jenkins/view/ROOT/job/root-makedoc-master/2679/parsed_console/

**Comment by couet** [comment]
> "bits" error also appears on https://lcgapp-services.cern.ch/root-jenkins/view/ROOT/job/root-makedoc-master/2679/parsed_console/

Yes I am aware

**Comment by eguiraud** [comment]
That's a problem with current master that should be fixed soon, a workaround is configuring the build with `-Druntime_cxxmodules=OFF`. See also https://github.com/root-project/root/pull/10498#issuecomment-1117088808

**Comment by eguiraud** [comment]
About the original issue. @ezradlesser why are you building ROOT from source? You can use one of the pre-compiled binaries in WSL, or use the conda package. See https://root.cern/install .

**Comment by ferdymercury** [comment]
There are Ubuntu 22 binaries for https://root.cern/releases/release-62602/ but not for 6.24/06

**Comment by eguiraud** [comment]
..and they are built for Python 3

**Comment by eguiraud** [comment]
The `bits/utility` compilation error has been fixed in latest master by @hahnjo

**Comment by ezradlesser** [comment]
Ah! I missed that there was a binary available for Ubuntu 22 of v6-26-02. Many thanks @ferdymercury for pointing this out, and also @eguiraud for clarifying that it is built for Python 3. So far it "just works" :)
Please feel free to close this issue at your discretion (assuming there is no intent to adding Ubuntu 22 support previous minor versions).

**Comment by eguiraud** [comment]
Closing this as v6.24.06 is not tested/released for Ubuntu 22, and @ezradlesser is happy with our pre-compiled binaries for v6.26. I am not completely sure whether a future v6.24.08 will support Ubuntu 22 or not, but that's a different issue.
