### PR TITLE
[io] Don't use `R__ALWAYS_INLINE` In TBufferJSON

### PR DESCRIPTION
**Pull request by guitargeek**
The `R__ALWAYS_INLINE` macro was introduced by commit b7c9be5 in TBufferJSON. However, it breaks the build with GCC and the `-Og` flag, for debug-compatible optimizations:

```txt
In member function ‘void TBufferJSON::JsonWriteFastArray(const T*, Int_t, const char*, void (TBufferJSON::*)(const T*, Int_t, const char*)) [with T = bool]’,
    inlined from ‘virtual void TBufferJSON::WriteFastArray(const Bool_t*, Int_t)’ at /home/rembserj/spaces/master-debug/root/src/root/io/io/src/TBufferJSON.cxx:3296:22:
/home/rembserj/spaces/master-debug/root/src/root/io/io/src/TBufferJSON.cxx:3034:23: error: inlining failed in call to ‘always_inline’ ‘void TBufferJSON::JsonWriteArrayCompress(const T*, Int_t, const char*) [with T = bool]’: function not considered for inlining
 3034 | R__ALWAYS_INLINE void TBufferJSON::JsonWriteArrayCompress(const T *vname, Int_t arrsize, const char *typname)
```

Libraries other than ROOT have also encountered similar problems: https://github.com/Cyan4973/xxHash/pull/804

The `R__ALWAYS_INLINE` macro is probably not necessary for these templated functions, because the compiler figures out itself whether it's worth to inline the templated functions or not.

### CODE REVIEW

**Review by linev — APPROVED** [review]
I hope this will not affect performance.

**Comment by guitargeek** [comment]
I checked the performance with this code snippet:
```c++
for (int i = 0; i < 1000000; ++i) {
   std::vector<int> vect(20);
   auto json = TBufferJSON::ToJSON(&vect);
}
```
fluctuates between 2.95 and 3.10 seconds in the ROOT interpreter, both with and without this PR.

**Comment by linev** [comment]
Sorry, I meant test vector size 10^7.
```
   std::vector<int> vect(10000000);
   auto json = TBufferJSON::ToJSON(&vect);
```
Here real inline-ing should save a lot of function calls

**Comment by linev** [comment]
Then its fine.
