### ISSUE TITLE
Root v6.24/06 using XrdSysDNS: Failure to compile using g++ 10.3.1

### ISSUE THREAD

**Issue by peter-jansson** [root-project/root#9173]
```
.../root_build/XROOTD-prefix/src/XROOTD/src/XrdSys/XrdSysDNS.cc: In 
static member function 'static char* XrdSysDNS::Peername(int, sockaddr*, char**)
':                                                                              
.../root_build/XROOTD-prefix/src/XROOTD/src/XrdSys/XrdSysDNS.cc:704:50: error: invalid conversion from 'int*' to 'socklen_t*' {aka 'unsigned int*'} [-fpermissive]
  704 |    if (getpeername(snum, (struct sockaddr *)sap, &addrlen) < 0)
      |                                                  ^~~~~~~~
      |                                                  |
      |                                                  int*
```

XrdSysDNS was deprecated in xrootd. Perhaps either add cast to socklen_t* on the third parameter or update to xrootd 5.3.2?

**Comment by peter-jansson** [comment]
I have tried to add "-fpermissive" to the compilation flags, then the XRootd build fails for another reason (some issue with <netdb.h> and an undefined call to the innetgr function). Maybe Alpine Linux is too "minimized" for Root?

**Comment by simonmichal** [comment]
Hi guys, the `XrdSysDNS` has been removed completely (https://github.com/xrootd/xrootd/commit/3d88fba139aa3384fd32a51cd1104db7e814bb05#diff-5101a8169c50b1ce76dbe0883bb868ac945b9de192313d56a0acdb5ad84fb484) as it has been deprecated for long time and replaced by `XrdNetAddrInfo` (AFAIR). I would advice moving to a newer version of xrootd.

**Comment by peter-jansson** [comment]
I suppose this will be handled by #7335.

**Comment by peter-jansson** [comment]
Same issue remain in 6.26/00.

**Comment by peter-jansson** [comment]
The output using [this build script](https://github.com/peter-jansson/appnuc/blob/eeb736f4137591f86a2070231f3fb1e8b3d7c8a9/scripts/install-root.sh) is available [here](https://github.com/peter-jansson/appnuc/runs/5468207882?check_suite_focus=true).  The log indicated more error log information in a XROOTD build log file, which is copy/pasted below. It is indeed v5.4.1 but some other error compared to before in this issue thread. pthread libraries missing?

```
[I] No git repository info found. Trying to interpret VERSION_INFO
[I] Using the user supplied version: v5.4.1
[I] src/XrdVersion.hh successfully generated
In file included from /.../root_build/builtins/xrootd/XROOTD-prefix/src/XROOTD/src/XrdSys/XrdSysE2T.cc:35:
/.../root_build/builtins/xrootd/XROOTD-prefix/src/XROOTD/src/./XrdSys/XrdSysPthread.hh: In constructor 'XrdSysRWLock::XrdSys
RWLock(XrdSysRWLock::PrefType)':
/tmp/tmp.aDEHad/root_build/builtins/xrootd/XROOTD-prefix/src/XROOTD/src/./XrdSys/XrdSysPthread.hh:357:30: error: 'PTHREAD_RWLOCK_PREFER
_WRITER_NONRECURSIVE_NP' was not declared in this scope
  357 |                              PTHREAD_RWLOCK_PREFER_WRITER_NONRECURSIVE_NP);
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/.../root_build/builtins/xrootd/XROOTD-prefix/src/XROOTD/src/./XrdSys/XrdSysPthread.hh:356:22: error: 'pthread_rwlockattr_se
tkind_np' was not declared in this scope; did you mean 'pthread_rwlockattr_setpshared'?
  356 |                      pthread_rwlockattr_setkind_np(&attr,
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                      pthread_rwlockattr_setpshared
/.../root_build/builtins/xrootd/XROOTD-prefix/src/XROOTD/src/./XrdSys/XrdSysPthread.hh: In member function 'void XrdSysRWLoc
k::ReInitialize(XrdSysRWLock::PrefType)':
/.../root_build/builtins/xrootd/XROOTD-prefix/src/XROOTD/src/./XrdSys/XrdSysPthread.hh:373:22: error: 'PTHREAD_RWLOCK_PREFER
_WRITER_NONRECURSIVE_NP' was not declared in this scope
  373 |                      PTHREAD_RWLOCK_PREFER_WRITER_NONRECURSIVE_NP);
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/.../root_build/builtins/xrootd/XROOTD-prefix/src/XROOTD/src/./XrdSys/XrdSysPthread.hh:372:3: error: 'pthread_rwlockattr_set
kind_np' was not declared in this scope; did you mean 'pthread_rwlockattr_setpshared'?
  372 |   pthread_rwlockattr_setkind_np(&attr,
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |   pthread_rwlockattr_setpshared
make[5]: *** [src/CMakeFiles/XrdUtils.dir/build.make:104: src/CMakeFiles/XrdUtils.dir/XrdSys/XrdSysE2T.cc.o] Error 1
make[4]: *** [CMakeFiles/Makefile2:814: src/CMakeFiles/XrdUtils.dir/all] Error 2
make[3]: *** [Makefile:136: all] Error 2
```

**Comment by peter-jansson** [comment]
I believe the latest issue is indeed a portability issue of XRootD and have [opened an issue](https://github.com/xrootd/xrootd/issues/1645) in XRootD’s repository.
