### PR TITLE
Fix Mac compilation error

### PR DESCRIPTION
**Pull request by ferdymercury**
cpu_set_t is not available on MacOS, only linux

# This Pull request:

## Changes or fixes:
compilation error introduced in https://github.com/root-project/root/pull/8557

### CODE REVIEW

**Comment by bellenot** [comment]
@phsft-bot build

**Review by Axel-Naumann — APPROVED** [review]

**Comment by Axel-Naumann** [comment]
We try to keep ROOT platform independent, this isn't helping :-/ I'll merge this as a stop-gap solution, but I'd like you @ferdymercury and @pcanal to consider reverting this feature. I am not sure I have seen any discussion on motivation, and why the use of e.g. tbb isn't a more appropriate solution.

**Comment by ferdymercury** [comment]
> We try to keep ROOT platform independent, this isn't helping :-/ I'll merge this as a stop-gap solution, but I'd like you @ferdymercury and @pcanal to consider reverting this feature. I am not sure I have seen any discussion on motivation, and why the use of e.g. tbb isn't a more appropriate solution.

Hi, the discussion is here: https://root-forum.cern.ch/t/performance-effects-in-a-root-based-data-acquisition/45519/3, I am developing a 40Gbps DAQ system where readout performance is critical to not lose data. Depending on which CPU the DAQ thread is located, the readout is fast enough to not lose any data. That's why setting CPU affinity was proposed. Without it, some readouts were not fast enough to catch up with the data rate.

I do not know about TBB, thus not sure if it would be better or worse.

Just as a side note, for my application, I do not need highly parallel tasks, I just need two threads (one for the GUI, one for the DAQ). If I do not set the affinity, Linux puts them both on the same CPU and thus the DAQ readout performance is reduced.
