### PR TITLE
[Backport][6.18] Compilation failure on Centos7 due to xrootd5

### LINKED ISSUE #6779: Compilation failure on Centos7 due to xrootd5 in v6.18
### Describe the bug

Our centos7 nightly builds fail with the following errors:

```
01:46:28 In file included from /mnt/build/jenkins/night/LABEL/ROOT-centos7/SPEC/noimt/V/6-18/root/proof/proofd/src/XrdProofConn.cxx:34:0:
01:46:28 /mnt/build/jenkins/night/LABEL/ROOT-centos7/SPEC/noimt/V/6-18/root/proof/proofd/inc/XrdProofConn.h:140:4: error: ‘XReqErrorType’ does not name a type
01:46:28     XReqErrorType       LowWrite(XPClientRequest *, const void *, int);
01:46:28     ^
01:46:28 In file included from /mnt/build/jenkins/night/LABEL/ROOT-centos7/SPEC/noimt/V/6-18/root/proof/proofd/src/XrdProofConn.cxx:47:0:
01:46:28 /usr/include/xrootd/XrdSec/XrdSecInterface.hh:611:25: warning: unused parameter ‘entity’ [-Wunused-parameter]
01:46:28  virtual bool            PostProcess(XrdSecEntity  &entity,
01:46:28                          ^
01:46:28 /usr/include/xrootd/XrdSec/XrdSecInterface.hh:611:25: warning: unused parameter ‘einfo’ [-Wunused-parameter]
01:46:28 /mnt/build/jenkins/night/LABEL/ROOT-centos7/SPEC/noimt/V/6-18/root/proof/proofd/src/XrdProofConn.cxx: In member function ‘XrdClientMessage* XrdProofConn::SendRecv(XPClientRequest*, const void*, char**)’:
01:46:28 /mnt/build/jenkins/night/LABEL/ROOT-centos7/SPEC/noimt/V/6-18/root/proof/proofd/src/XrdProofConn.cxx:551:41: error: ‘LowWrite’ was not declared in this scope
01:46:28     if (LowWrite(req, reqData, reqDataLen) != kOK) {
01:46:28                                          ^
01:46:28 /mnt/build/jenkins/night/LABEL/ROOT-centos7/SPEC/noimt/V/6-18/root/proof/proofd/src/XrdProofConn.cxx:551:46: error: ‘kOK’ was not declared in this scope
01:46:28     if (LowWrite(req, reqData, reqDataLen) != kOK) {
01:46:28                                               ^
01:46:28 /mnt/build/jenkins/night/LABEL/ROOT-centos7/SPEC/noimt/V/6-18/root/proof/proofd/src/XrdProofConn.cxx: At global scope:
01:46:28 /mnt/build/jenkins/night/LABEL/ROOT-centos7/SPEC/noimt/V/6-18/root/proof/proofd/src/XrdProofConn.cxx:777:1: error: ‘XReqErrorType’ does not name a type
01:46:28  XReqErrorType XrdProofConn::LowWrite(XPClientRequest *req, const void* reqData,
01:46:28  ^
01:46:28 /mnt/build/jenkins/night/LABEL/ROOT-centos7/SPEC/noimt/V/6-18/root/proof/proofd/src/XrdProofConn.cxx: In member function ‘XrdProofConn::ESrvType XrdProofConn::DoHandShake(XrdClientPhyConnection*)’:
01:46:28 /mnt/build/jenkins/night/LABEL/ROOT-centos7/SPEC/noimt/V/6-18/root/proof/proofd/src/XrdProofConn.cxx:1005:4: error: ‘ServerResponseType’ was not declared in this scope
01:46:28     ServerResponseType type;
01:46:28     ^
01:46:28 /mnt/build/jenkins/night/LABEL/ROOT-centos7/SPEC/noimt/V/6-18/root/proof/proofd/src/XrdProofConn.cxx:1005:23: error: expected ‘;’ before ‘type’
01:46:28     ServerResponseType type;
01:46:28                        ^
01:46:28 /mnt/build/jenkins/night/LABEL/ROOT-centos7/SPEC/noimt/V/6-18/root/proof/proofd/src/XrdProofConn.cxx:1006:17: error: ‘type’ was not declared in this scope
01:46:28     len = sizeof(type);
01:46:28                  ^
01:46:28 /mnt/build/jenkins/night/LABEL/ROOT-centos7/SPEC/noimt/V/6-18/root/proof/proofd/src/XrdProofConn.cxx:1062:1: warning: control reaches end of non-void function [-Wreturn-type]
01:46:28  }
01:46:28  ^
```

which seem caused by an update in the xrootd version (now version 5). ROOT has [some known issues](https://sft.its.cern.ch/jira/browse/ROOT-10910) with xrootd5, although this failure mode is not the same as in those cases.

[These](root-project/root#6226) are the changes that @oshadura backported to 6.22 to fix xrootd5 support there.
I don't know whether those changes might break support for older xrootd versions instead (I just haven't looked into it).

### To Reproduce

The failures are happening every night, e.g. see https://lcgapp-services.cern.ch/root-jenkins/view/ROOT%20Nightly/job/root-nightly-v6-18-00-patches/406/LABEL=ROOT-centos7,SPEC=noimt,V=6-18/consoleFull

### PR DESCRIPTION
**Pull request by stwunsch**
This PR collects all required commits to make xrd5 work on centos7 with ROOT 6.18.

Fixes #6779

### CODE REVIEW

**Comment by stwunsch** [comment]
Argh, made the PR against master
