### ISSUE TITLE
ROOT/LLVM fails with C++20 and new GCC 14.3/15.1

### ISSUE THREAD

**Issue by smuzaffar** [root-project/root#18939]
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

ROOT failed[a] to build using newer GCC 14.3.1. Searching net I found
 
- https://github.com/llvm/llvm-project/issues/139072
- https://gcc.gnu.org/gcc-15/porting_to.html#cxx20-iterators

Any idea how to fix/avoid this build error? 
[a]
```
root-6.32.13/interpreter/llvm-project/llvm/include/llvm/ADT/iterator.h:272:16: error: static assertion failed: The '-' operator is only defined for random access iterators.
  272 |         BaseT::IsRandomAccess,
      |                ^~~~~~~~~~~~~~
root-6.32.13/interpreter/llvm-project/llvm/include/llvm/ADT/iterator.h:272:16: note: 'llvm::iterator_facade_base<llvm::StringMapKeyIterator<llvm::StringRef>, std::forward_iterator_tag, llvm::StringRef, long int, llvm::StringRef*, llvm::StringRef&>::IsRandomAccess' evaluates to false
root-6.32.13/interpreter/llvm-project/llvm/include/llvm/ADT/iterator.h:274:14: error: no match for 'operator-' (operand types are 'const llvm::StringMapConstIterator<llvm::StringRef>' and 'const llvm::StringMapConstIterator<llvm::StringRef>')
  274 |     return I - RHS.I;
```

### Reproducer

Build ROOT 6.32 (or root master) using latest GCC 15.1 or 14.3.1 with C++20

### ROOT version

ROOT 6.32

### Installation method

build from sources

### Operating system

Linux

### Additional context

Build ROOT for CMS offline software

**Comment by ferdymercury** [comment]
A backport of https://github.com/root-project/root/pull/17735 might help.

**Comment by pcanal** [comment]
master should have work due to https://github.com/root-project/root/pull/17735 which force llvm to C++17.  Which file failed to compile?

**Comment by dpiparo** [comment]
> A backport of [#17735](https://github.com/root-project/root/pull/17735) might help.

While this is correct, I would like to note that we decided not to port the change to the 6.32 series because cling uses LLVM 16 for that version and while some C++20 support is provided by LLVM 16, this is far less than the one provided by LLVM 18, used by 6.36.

**Comment by smuzaffar** [comment]
> master should have work due to [#17735](https://github.com/root-project/root/pull/17735) which force llvm to C++17. Which file failed to compile?

@pcanal , file which failed is `interpreter/llvm-project/clang/lib/Driver/ToolChains/Arch/X86.cpp` 

[a]
```
FAILED: interpreter/llvm-project/llvm/tools/clang/lib/Driver/CMakeFiles/obj.clangDriver.dir/ToolChains/Arch/X86.cpp.o
In file included from root-6.32.13/interpreter/
llvm-project/llvm/include/llvm/ADT/STLExtras.h:24,
                 from root-6.32.13/interpreter/llvm-project/llvm/include/llvm/ADT/ArrayRef.h:14,
                 from root-6.32.13/interpreter/llvm-project/clang/include/clang/Basic/Diagnostic.h:21,
                 from root-6.32.13/interpreter/llvm-project/clang/include/clang/Driver/Driver.h:12,
                 from root-6.32.13/interpreter/llvm-project/clang/lib/Driver/ToolChains/Arch/X86.h:12,
                 from root-6.32.13/interpreter/llvm-project/clang/lib/Driver/ToolChains/Arch/X86.cpp:9:
root-6.32.13/interpreter/llvm-project/llvm/include/llvm/ADT/iterator.h: In instantiation of 'llvm::iterator_adaptor_base<DerivedT, WrappedIteratorT, IteratorCategoryT, T, DifferenceTypeT, PointerT, ReferenceT>::difference_type llvm::iterator_adaptor_base<DerivedT, WrappedIteratorT, IteratorCategoryT, T, DifferenceTypeT, PointerT, ReferenceT>::operator-(const DerivedT&) const [with DerivedT = llvm::StringMapKeyIterator<llvm::StringRef>; WrappedIteratorT = llvm::StringMapConstIterator<llvm::StringRef>; IteratorCategoryT = std::forward_iterator_tag; T = llvm::StringRef; DifferenceTypeT = long int; PointerT = llvm::StringRef*; ReferenceT = llvm::StringRef&; difference_type = long int]':
gcc/14.3.1-724da22786638848892aa9ded8fcd995/include/c++/14.3.1/bits/ranges_base.h:961:23:   required from 'constexpr std::iter_difference_t<typename std::decay<_Tp>::type> std::ranges::__distance_fn::operator()(_It&&, _Sent) const [with _It = llvm::StringMapKeyIterator<llvm::StringRef>&; _Sent = llvm::StringMapKeyIterator<llvm::StringRef>; std::iter_difference_t<typename std::decay<_Tp>::type> = long int; typename std::decay<_Tp>::type = llvm::StringMapKeyIterator<llvm::StringRef>]'
  961 |       { return __last - static_cast<const decay_t<_It>&>(__first); }
      |                ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gcc/14.3.1-724da22786638848892aa9ded8fcd995/include/c++/14.3.1/bits/stl_vector.h:718:44:   required from 'constexpr std::vector<_Tp, _Alloc>::vector(_InputIterator, _InputIterator, const allocator_type&) [with _InputIterator = llvm::StringMapKeyIterator<llvm::StringRef>; <template-parameter-2-2> = void; _Tp = llvm::StringRef; _Alloc = std::allocator<llvm::StringRef>; allocator_type = std::allocator<llvm::StringRef>]'
  718 |                 = static_cast<size_type>(ranges::distance(__first, __last));
      |                                          ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
root-6.32.13/interpreter/llvm-project/clang/lib/Driver/ToolChains/Arch/X86.cpp:59:61:   required from here
   59 |                                         ArchMap.keys().end()};
      |                                                             ^
root-6.32.13/interpreter/llvm-project/llvm/include/llvm/ADT/iterator.h:272:16: error: static assertion failed: The '-' operator is only defined for random access iterators.
  272 |         BaseT::IsRandomAccess,
      |                ^~~~~~~~~~~~~~
root-6.32.13/interpreter/llvm-project/llvm/include/llvm/ADT/iterator.h:272:16: note: 'llvm::iterator_facade_base<llvm::StringMapKeyIterator<llvm::StringRef>, std::forward_iterator_tag, llvm::StringRef, long int, llvm::StringRef*, llvm::StringRef&>::IsRandomAccess' evaluates to false
root-6.32.13/interpreter/llvm-project/llvm/include/llvm/ADT/iterator.h:274:14: error: no match for 'operator-' (operand types are 'const llvm::StringMapConstIterator<llvm::StringRef>' and 'const llvm::StringMapConstIterator<llvm::StringRef>')
  274 |     return I - RHS.I;
```

**Comment by smuzaffar** [comment]
Note that this also fails for latest GCC 13 updates (which will go in the next 13.4 release , [soon to come out](https://gcc.gnu.org/pipermail/gcc/2025-May/246101.html))

**Comment by smuzaffar** [comment]
Hi, update on GCC 13.4.1 , PR tests for https://github.com/cms-sw/cmsdist/pull/9914, i.e. latest GCC 13.3.1, were successful. So CMSSW can survive without backporting https://github.com/root-project/root/pull/17735 for ROOT 6.32 branch. Issue is with GCC 14 and 15 only and for those compilers we will move to ROOT 6.36.

So no need to backport https://github.com/root-project/root/pull/17735  for ROOT 6.32 branch

**Comment by pcanal** [comment]
Is the master working fine (hence can we close this issue?)

**Comment by smuzaffar** [comment]
> Is the master working fine (hence can we close this issue?)

I have tested ROOT 6.36 banch and it works with newer GCC 14.3.1 so I guess root master should work too. 

closing this issue now
