### ISSUE TITLE
Cannot import custom PDF into RooWorkspace

### ISSUE THREAD

**Issue by goi42** [root-project/root#7249]
- [x] Checked for duplicates

### Describe the bug

`RooWorkspace` is supposed to be able to store custom PDFs using `importClassCode`, but, even after setting `Impl` and `Decl` directories, a workspace with a custom PDF will crash on opening.

### Expected behavior

Ideally, just
```python
ws.importClassCode("RooSDSCBShape.cxx")
```
should be sufficient.

### To Reproduce

The `.cxx` and `.h` files can be found on the [forum](https://root-forum.cern.ch/t/import-custom-pdf-in-rooworkspace/43478?u=mwilkins).
```python
import os

import ROOT as r

# declare PDF
r.gROOT.ProcessLine(".x RooSDSCBShape.cxx")

# manually set Decl and Impl files
cls = r.TClass.GetClass("RooSDSCBShape")
cls.SetDeclFile(f"{os.getcwd()}/RooSDSCBShape.h", 0)
cls.SetImplFileName(f"{os.getcwd()}/RooSDSCBShape.cxx")

# store the class in a workspace
ws = r.RooWorkspace("ws")
ws.addClassDeclImportDir(os.getcwd())
ws.addClassImplImportDir(os.getcwd())
ws.importClassCode(cls)
ws.writeToFile("test.root")

# extract the class from the workspace
f = r.TFile.Open("test.root")
inws = f.Get("ws")
```

Output:
```
RooFit v3.60 -- Developed by Wouter Verkerke and David Kirkby 
                Copyright (C) 2000-2013 NIKHEF, University of California & Stanford University
                All rights reserved, please read http://roofit.sourceforge.net/license.txt

(RooSDSCBShape) An instance of RooSDSCBShape.
[#1] INFO:ObjectHandling -- RooWorkspace::autoImportClass(ws) importing code of class RooSDSCBShape from /<path/to>/RooSDSCBShape.cxx and /<path/to>/RooSDSCBShape.h
[#1] INFO:ObjectHandling -- RooWorkspace::CodeRepo::compileClasses() creating code export directory .wscode.305a6bb0-6f9d-11eb-9678-a001a8c0beef.ws to extract coded embedded in workspace
[#1] INFO:ObjectHandling -- RooWorkspace::CodeRepo::compileClasses() Extracting declaration code of class RooSDSCBShape, file .wscode.305a6bb0-6f9d-11eb-9678-a001a8c0beef.ws/RooSDSCBShape.h
[#1] INFO:ObjectHandling -- RooWorkspace::CodeRepo::compileClasses() Extracting implementation code of class RooSDSCBShape, file .wscode.305a6bb0-6f9d-11eb-9678-a001a8c0beef.ws/RooSDSCBShape.cxx
[#1] INFO:ObjectHandling -- RooWorkspace::CodeRepo::compileClasses() Compiling code unit RooSDSCBShape to define class RooSDSCBShape
Info in <TMacOSXSystem::ACLiC>: creating shared library /<path/to>/Downloads/.wscode.305a6bb0-6f9d-11eb-9678-a001a8c0beef.ws/RooSDSCBShape_cxx.so
ld: library not found for -lCheckFix
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
Error in <ACLiC>: Executing 'cd "/<path/to>/Downloads/.wscode.305a6bb0-6f9d-11eb-9678-a001a8c0beef.ws" ; x86_64-apple-darwin13.4.0-clang++ -fPIC -c -O3 -DNDEBUG -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -fmessage-length=0 -I/<path/to>/opt/anaconda3/envs/aslsRun2_ana/include -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/root_1607274686894/work=/usr/local/src/conda/root_base-6.22.6 -fdebug-prefix-map=/<path/to>/opt/anaconda3/envs/aslsRun2_ana=/usr/local/src/conda-prefix -std=c++17 -Wc++11-narrowing -Wsign-compare -Wsometimes-uninitialized -Wconditional-uninitialized -Wheader-guard -Warray-bounds -Wcomment -Wtautological-compare -Wstrncat-size -Wloop-analysis -Wbool-conversion -m64 -pipe -W -Woverloaded-virtual -fsigned-char -fno-common -Qunused-arguments -pthread -stdlib=libc++  -I$ROOTSYS/include -I"/<path/to>/opt/anaconda3/envs/aslsRun2_ana/etc/" -I"/<path/to>/opt/anaconda3/envs/aslsRun2_ana/etc//cling" -I"/<path/to>/opt/anaconda3/envs/aslsRun2_ana/include/" -I"/<path/to>/opt/anaconda3/envs/aslsRun2_ana/include" -I"/<path/to>/opt/anaconda3/envs/aslsRun2_ana/include/python3.9"   -D__ACLIC__ "/<path/to>/Downloads/.wscode.305a6bb0-6f9d-11eb-9678-a001a8c0beef.ws/RooSDSCBShape_cxx_ACLiC_dict.cxx" ; x86_64-apple-darwin13.4.0-clang++ -O3 -DNDEBUG "/<path/to>/Downloads/.wscode.305a6bb0-6f9d-11eb-9678-a001a8c0beef.ws/RooSDSCBShape_cxx_ACLiC_dict.o" -dynamiclib -Wl,-headerpad_max_install_names -m64 -single_module -Wl,-dead_strip_dylibs -undefined dynamic_lookup   "-lfakelink" "/<path/to>/opt/anaconda3/envs/aslsRun2_ana/lib/libz.1.2.11.dylib" "/<path/to>/opt/anaconda3/envs/aslsRun2_ana/lib/liblzma.5.dylib" "/<path/to>/opt/anaconda3/envs/aslsRun2_ana/lib/libcrypto.1.1.dylib" "/<path/to>/opt/anaconda3/envs/aslsRun2_ana/lib/libsqlite3.0.dylib" "/<path/to>/opt/anaconda3/envs/aslsRun2_ana/lib/libssl.1.1.dylib" "-lnetwork" "-lpcap.A" "-ldns_services" "-lz.1" "-lcoretls_cfhelpers" "-lapple_nghttp2" "-lenergytrace" "-lsqlite3" "-lMobileGestalt" "-lcoretls" "-lxar.1" "-lcompression" "-larchive.2" "-lxml2.2" "-llzma.5" "-lbz2.1.0" "-liconv.2" "-lcharset.1" "-lCheckFix" "-lmecabra" "-lmecab" "-lgermantok" "-lThaiTokenizer" "-lChineseTokenizer" "-lcmph" "-lutil" "-lapp_launch_measurement" "-lxslt.1" "/<path/to>/opt/anaconda3/envs/aslsRun2_ana/lib/libcppyy3_9.6.22.06.so" "/<path/to>/opt/anaconda3/envs/aslsRun2_ana/lib/libcppyy_backend3_9.6.22.06.so" "/<path/to>/opt/anaconda3/envs/aslsRun2_ana/lib/libCore.6.22.06.so" "/<path/to>/opt/anaconda3/envs/aslsRun2_ana/lib/libc++.1.0.dylib" "/<path/to>/opt/anaconda3/envs/aslsRun2_ana/lib/libpcre.1.dylib" "/<path/to>/opt/anaconda3/envs/aslsRun2_ana/lib/libxxhash.0.8.0.dylib" "/<path/to>/opt/anaconda3/envs/aslsRun2_ana/lib/liblz4.1.9.2.dylib" "/<path/to>/opt/anaconda3/envs/aslsRun2_ana/lib/libzstd.1.4.5.dylib" "-lspindump" "-late" "-lexpat.1" "-lIOReport" "-lSMC" "-lmis" "-lheimdal-asn1" "-lAudioStatistics" "-lperfcheck" "/<path/to>/opt/anaconda3/envs/aslsRun2_ana/lib/libRIO.6.22.06.so" "/<path/to>/opt/anaconda3/envs/aslsRun2_ana/lib/libThread.6.22.06.so" "/<path/to>/opt/anaconda3/envs/aslsRun2_ana/lib/libCling.6.22.06.so" "/<path/to>/opt/anaconda3/envs/aslsRun2_ana/lib/libffi.7.dylib" "/<path/to>/opt/anaconda3/envs/aslsRun2_ana/lib/libROOTPythonizations3_9.6.22.06.so" "/<path/to>/opt/anaconda3/envs/aslsRun2_ana/lib/libTree.6.22.06.so" "/<path/to>/opt/anaconda3/envs/aslsRun2_ana/lib/libNet.6.22.06.so" "/<path/to>/opt/anaconda3/envs/aslsRun2_ana/lib/libImt.6.22.06.so" "/<path/to>/opt/anaconda3/envs/aslsRun2_ana/lib/libtbb.dylib" "/<path/to>/opt/anaconda3/envs/aslsRun2_ana/lib/libRooFitCore.6.22.06.so" "/<path/to>/opt/anaconda3/envs/aslsRun2_ana/lib/libMinuit.6.22.06.so" "/<path/to>/opt/anaconda3/envs/aslsRun2_ana/lib/libFoam.6.22.06.so" "/<path/to>/opt/anaconda3/envs/aslsRun2_ana/lib/libGraf.6.22.06.so" "/<path/to>/opt/anaconda3/envs/aslsRun2_ana/lib/libHist.6.22.06.so" "/<path/to>/opt/anaconda3/envs/aslsRun2_ana/lib/libMatrix.6.22.06.so" "/<path/to>/opt/anaconda3/envs/aslsRun2_ana/lib/libMathCore.6.22.06.so" "-lsandbox.1" "-lCoreStorage" "-lcsfde" "-lMatch.1" -o "/<path/to>/Downloads/.wscode.305a6bb0-6f9d-11eb-9678-a001a8c0beef.ws/RooSDSCBShape_cxx.so"' failed!
[#0] ERROR:ObjectHandling -- RooWorkspace::CodeRepo::compileClasses() ERROR compiling class RooSDSCBShape, to fix this you can do the following: 
  1) Fix extracted source code files in directory .wscode.305a6bb0-6f9d-11eb-9678-a001a8c0beef.ws/
  2) In clean ROOT session compiled fixed classes by hand using '.x .wscode.305a6bb0-6f9d-11eb-9678-a001a8c0beef.ws/ClassName.cxx+'
  3) Reopen file with RooWorkspace with broken source code in UPDATE mode. Access RooWorkspace to force loading of class
     Broken instances in workspace will _not_ be compiled, instead precompiled fixed instances will be used.
  4) Reimport fixed code in workspace using 'RooWorkspace::importClassCode("*",kTRUE)' method, Write() updated workspace to file and close file
  5) Reopen file in clean ROOT session to confirm that problems are fixed
```

### Setup

ROOT version 6.22/06 on macOS, obtained from conda-forge.

### Additional context

See the forum post [here](https://root-forum.cern.ch/t/import-custom-pdf-in-rooworkspace/43478?u=mwilkins).

In my view, `importClassCode` ought to be sufficient on its own, but in any case, once this is resolved, the required sequence of `RooWorkspace::addClassDeclImportDir`, `RooWorkspace::addClassImplImportDir`, `RooWorkspace::importClassCode`, `TClass::SetDeclFile`, and `TClass::SetImplFileName` ought to appear in the documentation.

**Comment by guitargeek** [comment]
Hi @goi42, thanks for opening the issue and providing the code.

I could not reproduce your compilation error word-by-work in my ROOT 6.22 environment, but indeed I got an error as well.

In your code, I noticed you run:
```Python
r.gROOT.ProcessLine(".x RooSDSCBShape.cxx")
```
This [website about cling](https://root.cern/cling/) says that `.x` loads the file and then runs the function called `RooSDSCBShape` if it exists. I think it's better to use `.L`. That would be the constructor in this case, which you don't want to run. For me, I also get an error that functions are defined already when I load the `cxx` file.

So writing this line instead works for me:
```C++
r.gROOT.ProcessLine(".L RooSDSCBShape.h")
```

Could you please let me know if this also works for you?

On a sidenote: your custom class `SDSCBShape` is just a crystal ball with a single non-Gaussian tail on the right, no? We are working to shipping such a release also with the next ROOT version (see https://github.com/root-project/root/issues/7258), so you might not have to go through this custom-classes hassle anymore in the future.

**Comment by goi42** [comment]
Hi @guitargeek,

Thanks for looking into this. Unfortunately, I have the same error after making the changes you suggest.

```python
import os

import ROOT as r

# declare PDF
r.gROOT.ProcessLine(".L RooSDSCBShape.h")

# manually set Decl and Impl files
cls = r.TClass.GetClass("RooSDSCBShape")
cls.SetDeclFile(f"{os.getcwd()}/RooSDSCBShape.h", 0)
cls.SetImplFileName(f"{os.getcwd()}/RooSDSCBShape.cxx")

# store the class in a workspace
ws = r.RooWorkspace("ws")
ws.addClassDeclImportDir(os.getcwd())
ws.addClassImplImportDir(os.getcwd())
ws.importClassCode(cls)
ws.writeToFile("test.root")

# extract the class from the workspace
f = r.TFile.Open("test.root")
inws = f.Get("ws")
```
results in
```

RooFit v3.60 -- Developed by Wouter Verkerke and David Kirkby 
                Copyright (C) 2000-2013 NIKHEF, University of California & Stanford University
                All rights reserved, please read http://roofit.sourceforge.net/license.txt

[#1] INFO:ObjectHandling -- RooWorkspace::autoImportClass(ws) importing code of class RooSDSCBShape from /Users/michael/Downloads/RooSDSCBShape.cxx and /Users/michael/Downloads/RooSDSCBShape.h
[#1] INFO:ObjectHandling -- RooWorkspace::CodeRepo::compileClasses() creating code export directory .wscode.4edcf1dc-72c9-11eb-94e5-a001a8c0beef.ws to extract coded embedded in workspace
[#1] INFO:ObjectHandling -- RooWorkspace::CodeRepo::compileClasses() Extracting declaration code of class RooSDSCBShape, file .wscode.4edcf1dc-72c9-11eb-94e5-a001a8c0beef.ws/RooSDSCBShape.h
[#1] INFO:ObjectHandling -- RooWorkspace::CodeRepo::compileClasses() Extracting implementation code of class RooSDSCBShape, file .wscode.4edcf1dc-72c9-11eb-94e5-a001a8c0beef.ws/RooSDSCBShape.cxx
[#1] INFO:ObjectHandling -- RooWorkspace::CodeRepo::compileClasses() Compiling code unit RooSDSCBShape to define class RooSDSCBShape
Info in <TMacOSXSystem::ACLiC>: creating shared library /Users/michael/Downloads/.wscode.4edcf1dc-72c9-11eb-94e5-a001a8c0beef.ws/RooSDSCBShape_cxx.so
ld: library not found for -lCheckFix
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
Error in <ACLiC>: Executing 'cd "/Users/michael/Downloads/.wscode.4edcf1dc-72c9-11eb-94e5-a001a8c0beef.ws" ; x86_64-apple-darwin13.4.0-clang++ -fPIC -c -O3 -DNDEBUG -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -fmessage-length=0 -I/Users/michael/opt/anaconda3/envs/aslsRun2_ana/include -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/root_1607274686894/work=/usr/local/src/conda/root_base-6.22.6 -fdebug-prefix-map=/Users/michael/opt/anaconda3/envs/aslsRun2_ana=/usr/local/src/conda-prefix -std=c++17 -Wc++11-narrowing -Wsign-compare -Wsometimes-uninitialized -Wconditional-uninitialized -Wheader-guard -Warray-bounds -Wcomment -Wtautological-compare -Wstrncat-size -Wloop-analysis -Wbool-conversion -m64 -pipe -W -Woverloaded-virtual -fsigned-char -fno-common -Qunused-arguments -pthread -stdlib=libc++  -I$ROOTSYS/include -I"/Users/michael/opt/anaconda3/envs/aslsRun2_ana/etc/" -I"/Users/michael/opt/anaconda3/envs/aslsRun2_ana/etc//cling" -I"/Users/michael/opt/anaconda3/envs/aslsRun2_ana/include/" -I"/Users/michael/opt/anaconda3/envs/aslsRun2_ana/include" -I"/Users/michael/opt/anaconda3/envs/aslsRun2_ana/include/python3.9"   -D__ACLIC__ "/Users/michael/Downloads/.wscode.4edcf1dc-72c9-11eb-94e5-a001a8c0beef.ws/RooSDSCBShape_cxx_ACLiC_dict.cxx" ; x86_64-apple-darwin13.4.0-clang++ -O3 -DNDEBUG "/Users/michael/Downloads/.wscode.4edcf1dc-72c9-11eb-94e5-a001a8c0beef.ws/RooSDSCBShape_cxx_ACLiC_dict.o" -dynamiclib -Wl,-headerpad_max_install_names -m64 -single_module -Wl,-dead_strip_dylibs -undefined dynamic_lookup   "-lfakelink" "/Users/michael/opt/anaconda3/envs/aslsRun2_ana/lib/libz.1.2.11.dylib" "/Users/michael/opt/anaconda3/envs/aslsRun2_ana/lib/liblzma.5.dylib" "/Users/michael/opt/anaconda3/envs/aslsRun2_ana/lib/libcrypto.1.1.dylib" "/Users/michael/opt/anaconda3/envs/aslsRun2_ana/lib/libsqlite3.0.dylib" "/Users/michael/opt/anaconda3/envs/aslsRun2_ana/lib/libssl.1.1.dylib" "-lnetwork" "-lpcap.A" "-ldns_services" "-lz.1" "-lcoretls_cfhelpers" "-lapple_nghttp2" "-lenergytrace" "-lsqlite3" "-lMobileGestalt" "-lcoretls" "-lxar.1" "-lcompression" "-larchive.2" "-lxml2.2" "-llzma.5" "-lbz2.1.0" "-liconv.2" "-lcharset.1" "-lCheckFix" "-lmecabra" "-lmecab" "-lgermantok" "-lThaiTokenizer" "-lChineseTokenizer" "-lcmph" "-lutil" "-lapp_launch_measurement" "-lxslt.1" "/Users/michael/opt/anaconda3/envs/aslsRun2_ana/lib/libcppyy3_9.6.22.06.so" "/Users/michael/opt/anaconda3/envs/aslsRun2_ana/lib/libcppyy_backend3_9.6.22.06.so" "/Users/michael/opt/anaconda3/envs/aslsRun2_ana/lib/libCore.6.22.06.so" "/Users/michael/opt/anaconda3/envs/aslsRun2_ana/lib/libc++.1.0.dylib" "/Users/michael/opt/anaconda3/envs/aslsRun2_ana/lib/libpcre.1.dylib" "/Users/michael/opt/anaconda3/envs/aslsRun2_ana/lib/libxxhash.0.8.0.dylib" "/Users/michael/opt/anaconda3/envs/aslsRun2_ana/lib/liblz4.1.9.2.dylib" "/Users/michael/opt/anaconda3/envs/aslsRun2_ana/lib/libzstd.1.4.5.dylib" "-lspindump" "-late" "-lexpat.1" "-lIOReport" "-lSMC" "-lmis" "-lheimdal-asn1" "-lAudioStatistics" "-lperfcheck" "/Users/michael/opt/anaconda3/envs/aslsRun2_ana/lib/libRIO.6.22.06.so" "/Users/michael/opt/anaconda3/envs/aslsRun2_ana/lib/libThread.6.22.06.so" "/Users/michael/opt/anaconda3/envs/aslsRun2_ana/lib/libCling.6.22.06.so" "/Users/michael/opt/anaconda3/envs/aslsRun2_ana/lib/libffi.7.dylib" "/Users/michael/opt/anaconda3/envs/aslsRun2_ana/lib/libROOTPythonizations3_9.6.22.06.so" "/Users/michael/opt/anaconda3/envs/aslsRun2_ana/lib/libTree.6.22.06.so" "/Users/michael/opt/anaconda3/envs/aslsRun2_ana/lib/libNet.6.22.06.so" "/Users/michael/opt/anaconda3/envs/aslsRun2_ana/lib/libImt.6.22.06.so" "/Users/michael/opt/anaconda3/envs/aslsRun2_ana/lib/libtbb.dylib" "/Users/michael/opt/anaconda3/envs/aslsRun2_ana/lib/libRooFitCore.6.22.06.so" "/Users/michael/opt/anaconda3/envs/aslsRun2_ana/lib/libMinuit.6.22.06.so" "/Users/michael/opt/anaconda3/envs/aslsRun2_ana/lib/libFoam.6.22.06.so" "/Users/michael/opt/anaconda3/envs/aslsRun2_ana/lib/libGraf.6.22.06.so" "/Users/michael/opt/anaconda3/envs/aslsRun2_ana/lib/libHist.6.22.06.so" "/Users/michael/opt/anaconda3/envs/aslsRun2_ana/lib/libMatrix.6.22.06.so" "/Users/michael/opt/anaconda3/envs/aslsRun2_ana/lib/libMathCore.6.22.06.so" -o "/Users/michael/Downloads/.wscode.4edcf1dc-72c9-11eb-94e5-a001a8c0beef.ws/RooSDSCBShape_cxx.so"' failed!
[#0] ERROR:ObjectHandling -- RooWorkspace::CodeRepo::compileClasses() ERROR compiling class RooSDSCBShape, to fix this you can do the following: 
  1) Fix extracted source code files in directory .wscode.4edcf1dc-72c9-11eb-94e5-a001a8c0beef.ws/
  2) In clean ROOT session compiled fixed classes by hand using '.x .wscode.4edcf1dc-72c9-11eb-94e5-a001a8c0beef.ws/ClassName.cxx+'
  3) Reopen file with RooWorkspace with broken source code in UPDATE mode. Access RooWorkspace to force loading of class
     Broken instances in workspace will _not_ be compiled, instead precompiled fixed instances will be used.
  4) Reimport fixed code in workspace using 'RooWorkspace::importClassCode("*",kTRUE)' method, Write() updated workspace to file and close file
  5) Reopen file in clean ROOT session to confirm that problems are fixed
```

I make my conda environment using
```yaml
channels:
  - conda-forge
dependencies:
  - ipython
  - pandas=1.2.0
  - particle=0.14.0
  - root=6.22.6
  - root_pandas=0.7.0
```

Sidenote: I submitted #6172, which #7258 seeks to improve, but, as you note, it was never released. Hence my difficulty.

**Comment by guitargeek** [comment]
Ah I didn't realize that was you too! Nice, thanks a lot for your contribution! I'm thinking now how this can be further extended to cover also the class of crystal ball functions with asymmetric Gaussian core. Right, there has been no new release in some time.

Hmm what about this line in the error message here:
```
ld: library not found for -lCheckFix
```
What is `CheckFix`, is that also some custom library? I don't think it's part of ROOT. Maybe it's also a Mac related issue, which I can't reproduce on Linux unfortunately.

**Comment by guitargeek** [comment]
Just to add some documentation of the problem, here is the error that I have gotten before changing to `.L`:
```
[#1] INFO:ObjectHandling -- RooWorkspace::autoImportClass(ws) importing code of class RooSDSCBShape from /home/jonas/tmp/7249/RooSDSCBShape.cxx and /home/jonas/tmp/7249/RooSDSCBShape.h
[#1] INFO:ObjectHandling -- RooWorkspace::CodeRepo::compileClasses() creating code export directory .wscode.23b62870-72c4-11eb-8262-4c01a8c0beef.ws to extract coded embedded in workspace
[#1] INFO:ObjectHandling -- RooWorkspace::CodeRepo::compileClasses() Extracting declaration code of class RooSDSCBShape, file .wscode.23b62870-72c4-11eb-8262-4c01a8c0beef.ws/RooSDSCBShape.h
[#1] INFO:ObjectHandling -- RooWorkspace::CodeRepo::compileClasses() Extracting implementation code of class RooSDSCBShape, file .wscode.23b62870-72c4-11eb-8262-4c01a8c0beef.ws/RooSDSCBShape.cxx
[#1] INFO:ObjectHandling -- RooWorkspace::CodeRepo::compileClasses() Compiling code unit RooSDSCBShape to define class RooSDSCBShape
Info in <TUnixSystem::ACLiC>: creating shared library /home/jonas/tmp/7249/.wscode.23b62870-72c4-11eb-8262-4c01a8c0beef.ws/RooSDSCBShape_cxx.so
^CError in <ACLiC>: Executing '/usr/bin/rootcling -v0 "--lib-list-prefix=/home/jonas/tmp/7249/.wscode.23b62870-72c4-11eb-8262-4c01a8c0beef.ws/RooSDSCBShape_cxx_ACLiC_map" -f "/home/jonas/tmp/7249/.wscode.23b62870-72c4-11eb-8262-4c01a8c0beef.ws/RooSDSCBShape_cxx_ACLiC_dict.cxx" -I/usr/include -I"/etc/root" -I"/etc/root/cling" -I"/usr/include" -I"/build/root/src/build/include" -I"/usr/include/python3.9" -I"/build/root/src/build/include/" -I"/usr/include/freetype2" -D__ACLIC__  "/home/jonas/tmp/7249/.wscode.23b62870-72c4-11eb-8262-4c01a8c0beef.ws/RooSDSCBShape.cxx" "/home/jonas/tmp/7249/.wscode.23b62870-72c4-11eb-8262-4c01a8c0beef.ws/RooSDSCBShape_cxx_ACLiC_linkdef.h"' failed!
[#0] ERROR:ObjectHandling -- RooWorkspace::CodeRepo::compileClasses() ERROR compiling class RooSDSCBShape, to fix this you can do the following: 
  1) Fix extracted source code files in directory .wscode.23b62870-72c4-11eb-8262-4c01a8c0beef.ws/
  2) In clean ROOT session compiled fixed classes by hand using '.x .wscode.23b62870-72c4-11eb-8262-4c01a8c0beef.ws/ClassName.cxx+'
  3) Reopen file with RooWorkspace with broken source code in UPDATE mode. Access RooWorkspace to force loading of class
     Broken instances in workspace will _not_ be compiled, instead precompiled fixed instances will be used.
  4) Reimport fixed code in workspace using 'RooWorkspace::importClassCode("*",kTRUE)' method, Write() updated workspace to file and close file
  5) Reopen file in clean ROOT session to confirm that problems are fixed
```

**Comment by goi42** [comment]
I can confirm that I don't have this problem on a Linux x86_64 machine. It appears specific to Mac. I don't know what `CheckFix` is.

**Comment by SeungJunLee0** [comment]
you need to update or install xcode.

it worked for me.

**Comment by guitargeek** [comment]
That's very good that it worked for you! That's one reason to close this issue.

Another reason is that with ROOT 6.24, there is now the [RooCrystalBall class](https://github.com/root-project/root/blob/master/roofit/roofit/src/RooCrystalBall.cxx) in the release. So importing the custom `RooSDSCBShape` into a workspace should not be necessary.

Let me know if you have any other issue; feel free to reopen this or open a new one! But since I don't have a Mac, it might get a bit difficult :)

Cheers,
Jonas
